---

- name: Prepare
  tags: [always]
  hosts:
    - debian.stretch
  tasks:
    - name: Apt
      ansible.builtin.import_role:
        name: manala.roles.apt
      vars:
        manala_apt_preferences:
          - supervisor@backports
