---

- name: install > Stat bin
  stat:
    path: "{{ manala_gomplate_bin }}"
  register: __manala_gomplate_bin_stat_result

- name: install > Get latest version
  uri:
    url: https://github.com/hairyhenderson/gomplate/releases/latest
    return_content: false
  register: __manala_gomplate_version_latest
  when: (not __manala_gomplate_bin_stat_result.stat.exists)
        and (manala_gomplate_version is none)

- name: install > Install
  get_url:
    url: "{{ manala_gomplate_version|ternary(
      'https://github.com/hairyhenderson/gomplate/releases/download/v%s/gomplate_linux-amd64'|format(
        manala_gomplate_version
      ),
      'https://github.com/hairyhenderson/gomplate/releases/download/v%s/gomplate_linux-amd64'|format(
        __manala_gomplate_version_latest.url|default|regex_replace('(.*)(\\d\\.\\d\\.\\d)(.*)', '\\2')
      )
    ) }}"
    dest: "{{ manala_gomplate_bin }}"
    owner: root
    group: root
    mode: "0755"
  when: (not __manala_gomplate_bin_stat_result.stat.exists)
