---

- name: install > Stat bin
  stat:
    path: "{{ manala_gomplate_bin }}"
  register: __manala_gomplate_bin_stat_result

- name: install > Get latest version
  uri:
    url: https://github.com/hairyhenderson/gomplate/releases/latest
    return_content: false
  register: __manala_gomplate_version_latest
  when: (not __manala_gomplate_bin_stat_result.stat.exists)
        and (manala_gomplate_version is none)

- name: install > Set latest version
  set_fact:
    manala_gomplate_version: "{{ __manala_gomplate_version_latest.url | regex_replace('(.*)(\\d\\.\\d\\.\\d)(.*)', '\\2') }}"
  when: (not __manala_gomplate_bin_stat_result.stat.exists)
        and (manala_gomplate_version is none)

- name: install > Install
  get_url:
    url: "https://github.com/hairyhenderson/gomplate/releases/download/v{{ manala_gomplate_version }}/gomplate_linux-amd64"
    dest: "{{ manala_gomplate_bin }}"
    mode: 0755
  when: (not __manala_gomplate_bin_stat_result.stat.exists)
