---

# Requirements
- ansible.builtin.import_tasks: requirements.yml
  tags:
    - manala_postgresql
    - manala_postgresql.requirements

# Install
- ansible.builtin.import_tasks: install.yml
  tags:
    - manala_postgresql
    - manala_postgresql.install

# Config
- ansible.builtin.import_tasks: config.yml
  tags:
    - manala_postgresql
    - manala_postgresql.config

# Services
- ansible.builtin.import_tasks: services.yml
  tags:
    - manala_postgresql
    - manala_postgresql.services
    - manala.services

# Roles
- ansible.builtin.import_tasks: roles.yml
  tags:
    - manala_postgresql
    - manala_postgresql.roles

# Databases
- ansible.builtin.import_tasks: databases.yml
  tags:
    - manala_postgresql
    - manala_postgresql.databases

# Privileges
- ansible.builtin.import_tasks: privileges.yml
  tags:
    - manala_postgresql
    - manala_postgresql.privileges
