---

# Install
- ansible.builtin.import_tasks: install.yml
  tags:
    - manala_influxdb
    - manala_influxdb.install

# Dir
- ansible.builtin.import_tasks: dir.yml
  tags:
    - manala_influxdb
    - manala_influxdb.dir

# Config
- ansible.builtin.import_tasks: config.yml
  tags:
    - manala_influxdb
    - manala_influxdb.config

# Services
- ansible.builtin.import_tasks: services.yml
  tags:
    - manala_influxdb
    - manala_influxdb.services
    - manala.services

# Databases
- ansible.builtin.import_tasks: databases.yml
  tags:
    - manala_influxdb
    - manala_influxdb.databases

# Users
- ansible.builtin.import_tasks: users.yml
  tags:
    - manala_influxdb
    - manala_influxdb.users

# Privileges
- ansible.builtin.import_tasks: privileges.yml
  tags:
    - manala_influxdb
    - manala_influxdb.privileges
