---

###########
# Default #
###########

- name: Default
  tags: [default]
  hosts:
    - debian.stretch
  tasks:
    - block:  # noqa unnamed-task
        - name: Role
          ansible.builtin.import_role:
            name: manala.roles.maxscale
