---

# Install
- ansible.builtin.import_tasks: install.yml
  tags:
    - manala_rsyslog
    - manala_rsyslog.install

# Config
- ansible.builtin.import_tasks: config.yml
  tags:
    - manala_rsyslog
    - manala_rsyslog.config

# Configs
- ansible.builtin.import_tasks: configs.yml
  tags:
    - manala_rsyslog
    - manala_rsyslog.configs

# Services
- ansible.builtin.import_tasks: services.yml
  tags:
    - manala_rsyslog
    - manala_rsyslog.services
    - manala.services
