####################################################################
# !!! REMINDER !!!                                                 #
# Don't forget to run `manala up` each time you update this file ! #
####################################################################

manala:
    recipe: lazy.ansible

###########
# Project #
###########

project:
    name: manala-ansible-roles

##########
# System #
##########

system:
    dir: /srv/ansible_collections/manala/roles
    env_file:
        - .env.dist
        - .env
    docker: true
    ansible:
        version: 2.14.0
    ansible-lint:
        version: 6.9.0
    molecule:
        version: 4.0.3
        docker:
            version: 2.0.0
