####################################################################
# !!! REMINDER !!!                                                 #
# Don't forget to run `manala up` each time you update this file ! #
####################################################################

manala:
    recipe: lazy.ansible

###########
# Project #
###########

project:
    name: manala-ansible-roles

##########
# System #
##########

system:
    dir: /srv/ansible_collections/manala/roles
    env_file:
        - .env.dist
        - .env
    docker: true
    git:
        config: |
            # Silence false positive dubious ownership errors
            [safe]
            directory = *
    ansible:
        version: 2.15.5
        dependencies:
            # Collection community.docker
            - docker==6.1.3
    ansible-lint:
        version: 6.14.6
    molecule:
        version: 5.0.1
        dependencies:
            - molecule-plugins==23.5.0
            - molecule-plugins[docker]==23.5.0
