---

- name: redis restart
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - redis-server


- name: redis-sentinel restart
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - redis-sentinel
