---

# Configs
- ansible.builtin.import_tasks: configs.yml
  tags:
    - manala_apt
    - manala_apt.configs

# Install
- ansible.builtin.import_tasks: install.yml
  tags:
    - manala_apt
    - manala_apt.install

# Sources list
- ansible.builtin.import_tasks: sources_list.yml
  tags:
    - manala_apt
    - manala_apt.sources_list

# Preferences
- ansible.builtin.import_tasks: preferences.yml
  tags:
    - manala_apt
    - manala_apt.preferences

# Keys
- ansible.builtin.import_tasks: keys.yml
  tags:
    - manala_apt
    - manala_apt.keys

# Repositories
- ansible.builtin.import_tasks: repositories.yml
  tags:
    - manala_apt
    - manala_apt.repositories

# Packages
- ansible.builtin.import_tasks: packages.yml
  tags:
    - manala_apt
    - manala_apt.packages

# Holds
- ansible.builtin.import_tasks: holds.yml
  tags:
    - manala_apt
    - manala_apt.holds

# Update
- ansible.builtin.import_tasks: update.yml
  when: __manala_apt['update']
  tags:
    - manala_apt
    - manala_apt.update
    - manala.update
