---

- name: Repositories > Exclusive
  ansible.builtin.find:
    path: "{{ manala_apt_repositories_dir }}"
    file_type: file
    patterns: "*"
  changed_when: false
  register: __manala_apt_repositories_exclusive_find
  when: manala_apt_repositories_exclusive

- name: Repositories > Repositories presents
  ansible.builtin.template:
    src: repositories/_default.j2
    dest: "{{ item.file }}"
    owner: root
    group: root
    mode: "0644"
  loop: |
    {{ query(
      'manala.roles.apt_repositories',
      manala_apt_repositories,
      manala_apt_repositories_patterns,
      query(
          'manala.roles.apt_preferences',
          manala_apt_preferences,
          manala_apt_preferences_patterns,
          manala_apt_repositories_patterns,
          [],
          manala_apt_preferences_dir,
          manala_apt_preferences_defaults.template | default('preferences/_default.j2', true),
          wantstate='present'
      ),
      __manala_apt_repositories_exclusive_find.files | default([]),
      manala_apt_repositories_dir,
      wantstate='present'
    ) }}
  loop_control:
    label: "{{ {
        'file': item.file,
      } }}"
  register: __manala_apt_repositories_presents_results

# Note: for a seamless transition, legacy `.list` files are automatically removed.
- name: Repositories > Repositories legacy absents
  ansible.builtin.file:
    path: "{{ item.legacy_file }}"
    state: absent
  loop: |
    {{ query(
      'manala.roles.apt_repositories',
      manala_apt_repositories,
      manala_apt_repositories_patterns,
      query(
          'manala.roles.apt_preferences',
          manala_apt_preferences,
          manala_apt_preferences_patterns,
          manala_apt_repositories_patterns,
          [],
          manala_apt_preferences_dir,
          manala_apt_preferences_defaults.template | default('preferences/_default.j2', true),
          wantstate='present'
      ),
      __manala_apt_repositories_exclusive_find.files | default([]),
      manala_apt_repositories_dir,
      wantstate='present'
    ) | selectattr('legacy_file', 'defined') }}
  loop_control:
    label: "{{ {
        'file': item.legacy_file,
      } }}"
  register: __manala_apt_repositories_legacy_absents_results

- name: Repositories > Repositories absents
  ansible.builtin.file:
    path: "{{ item.file }}"
    state: absent
  loop: |
    {{ query(
      'manala.roles.apt_repositories',
      manala_apt_repositories,
      manala_apt_repositories_patterns,
      query(
          'manala.roles.apt_preferences',
          manala_apt_preferences,
          manala_apt_preferences_patterns,
          manala_apt_repositories_patterns,
          [],
          manala_apt_preferences_dir,
          manala_apt_preferences_defaults.template | default('preferences/_default.j2', true),
          wantstate='present'
      ),
      __manala_apt_repositories_exclusive_find.files | default([]),
      manala_apt_repositories_dir,
      wantstate='absent'
    ) }}
  loop_control:
    label: "{{ {
        'file': item.file,
      } }}"
  register: __manala_apt_repositories_absents_results

- name: Repositories > Update cache
  ansible.builtin.apt:  # noqa: no-handler
    update_cache: true
  when: __manala_apt_repositories_presents_results is changed
    or __manala_apt_repositories_legacy_absents_results is changed
    or __manala_apt_repositories_absents_results is changed
