---

# Install
- ansible.builtin.import_tasks: install.yml
  tags:
    - manala_cloud_init
    - manala_cloud_init.install

# Configs
- ansible.builtin.import_tasks: configs.yml
  tags:
    - manala_cloud_init
    - manala_cloud_init.configs
