---

- name: install > Directory
  ansible.builtin.file:
    path: "{{ manala_ohmyzsh_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: install > Git repository
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    version: master
    dest: "{{ manala_ohmyzsh_dir }}"
    update: "{{ __manala_ohmyzsh['update'] }}"
