---

- hosts: debian
  tags: [always]
  tasks:
    - name: Packages
      ansible.builtin.apt:
        name: [sudo]
        install_recommends: false
        update_cache: true
        cache_valid_time: 3600
