---

- name: install > Stat bin
  stat:
    path: "{{ manala_symfony_cli_bin }}"
  register: __manala_symfony_cli_bin_stat_result

- name: install > Get latest version
  uri:
    url: https://get.symfony.com/cli/LATEST
    return_content: true
  register: __manala_symfony_cli_version_latest
  when: (not __manala_symfony_cli_bin_stat_result.stat.exists)
        and (manala_symfony_cli_version is none)

- name: install > Install
  get_url:
    url: "{{ manala_symfony_cli_version|ternary(
      'https://github.com/symfony/cli/releases/download/v%s/symfony_linux_amd64'|format(
        manala_symfony_cli_version
      ),
      'https://github.com/symfony/cli/releases/download/v%s/symfony_linux_amd64'|format(
        __manala_symfony_cli_version_latest.content|default
      )
    ) }}"
    dest: "{{ manala_symfony_cli_bin }}"
    mode: 0755
  when: (not __manala_symfony_cli_bin_stat_result.stat.exists)
