---

# Install
- ansible.builtin.import_tasks: install.yml
  tags:
    - manala_sensu_go
    - manala_sensu_go.install

# Backend Config
- ansible.builtin.import_tasks: backend_config.yml
  tags:
    - manala_sensu_go
    - manala_sensu_go.backend_config

# Agent Config
- ansible.builtin.import_tasks: agent_config.yml
  tags:
    - manala_sensu_go
    - manala_sensu_go.agent_config

# Services
- ansible.builtin.import_tasks: services.yml
  tags:
    - manala_sensu_go
    - manala_sensu_go.services
    - manala.services
