---

- name: keepalived restart
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - keepalived

- name: keepalived reload
  ansible.builtin.service:
    name: "{{ item }}"
    state: reloaded
  loop:
    - keepalived
