---

###########
# Default #
###########

- name: Default
  tags: [default]
  hosts: debian
  tasks:
    - block:
        - name: Role
          ansible.builtin.import_role:
            name: manala.roles.ntp
      always:
        - name: Goss
          ansible.builtin.command:
            cmd: goss --gossfile - validate
            stdin: "{{ lookup('template', 'goss/default.yml.j2') }}"
