---

- hosts:
    - debian.stretch
    - debian.buster
  tags: [always]
  tasks:
    - name: Apt
      ansible.builtin.import_role:
        name: manala.roles.apt
      vars:
        manala_apt_preferences:
          - nodejs@nodesource_4
