---

- name: nginx restart
  ansible.builtin.command: nginx -t
  changed_when: true
  notify:
    - do nginx restart

- name: do nginx restart
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - nginx
