---

- name: Prepare
  tags: [always]
  hosts:
    - debian
    - "!debian.stretch"
  tasks:
    - name: Packages
      ansible.builtin.apt:
        name: [php-cli]
        install_recommends: false
        update_cache: true
        cache_valid_time: 3600
