---

# Install
- ansible.builtin.import_tasks: install.yml
  tags:
    - manala_maxscale
    - manala_maxscale.install

# Config
- ansible.builtin.import_tasks: config.yml
  tags:
    - manala_maxscale
    - manala_maxscale.config

# Configs
- ansible.builtin.import_tasks: configs.yml
  tags:
    - manala_maxscale
    - manala_maxscale.configs

# Users
- ansible.builtin.import_tasks: users.yml
  tags:
    - manala_maxscale
    - manala_maxscale.users

# Services
- ansible.builtin.import_tasks: services.yml
  tags:
    - manala_maxscale
    - manala_maxscale.services
