---

- name: sensu-backend restart
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - sensu-backend

- name: sensu-agent restart
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - sensu-agent
