---

- name: influxdb restart
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
  loop:
    - influxdb
  notify: influxdb start

- name: influxdb start
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
  loop:
    - influxdb
  register: __manala_influxdb_services
  until: __manala_influxdb_services is not failed
  retries: 12
  delay: 1
