---

###########
# Default #
###########

- name: Default
  tags: [default]
  hosts:
    - debian.stretch
    - debian.buster
  tasks:
    - block:
        - name: Role
          ansible.builtin.import_role:
            name: manala.roles.mongodb
      always:
        - name: Goss
          ansible.builtin.command:
            cmd: goss --gossfile - validate
            stdin: "{{ lookup('template', 'goss/default.yml.j2') }}"

##########
# Config #
##########

- name: Config
  tags: [config]
  hosts:
    - debian.stretch
    - debian.buster
  vars:
    tests_dir: /molecule/mongodb/config
  tasks:
    - name: Clean tests dir  # noqa risky-file-permissions
      ansible.builtin.file:
        path: "{{ tests_dir }}"
        state: "{{ item }}"
      loop: [absent, directory]
    - block:
        - name: Role - Dict
          ansible.builtin.import_role:
            # Play role fully on first run, so that handlers don't breaks
            name: manala.roles.mongodb
          vars:
            manala_mongodb_config_file: "{{ tests_dir }}/dict"
            manala_mongodb_config_template: ~
            manala_mongodb_config:
              port: 12345
        - name: Role - Content
          ansible.builtin.import_role:
            name: manala.roles.mongodb
            tasks_from: config
          vars:
            manala_mongodb_config_file: "{{ tests_dir }}/content"
            manala_mongodb_config_template: ~
            manala_mongodb_config: |
              Content
        - name: Role - Template
          ansible.builtin.import_role:
            name: manala.roles.mongodb
            tasks_from: config
          vars:
            manala_mongodb_config_file: "{{ tests_dir }}/template"
            manala_mongodb_config_template: fixtures/template.j2
            manala_mongodb_config: ~
      always:
        - name: Goss
          ansible.builtin.command:
            cmd: goss --gossfile - validate
            stdin: "{{ lookup('template', 'goss/config.yml.j2') }}"

#########
# Users #
#########

- name: Users
  tags: [users]
  hosts:
    - debian.stretch
    - debian.buster
  tasks:
    - block:
        - name: Role
          ansible.builtin.import_role:
            name: manala.roles.mongodb
          vars:
            manala_mongodb_users:
              - name: foo
                password: foo
                database: admin
                roles: userAdminAnyDatabase
                state: present
              - name: bar
                password: bar
                database: zerty
                roles: read
                login_database: admin
                login_user: dba
                login_password: bar
                state: ignore
              # Flatten
              -
                - name: baz
                  password: baz
                  database: admin
                  roles: userAdminAnyDatabase
                  state: present
      always:
        - name: Goss
          ansible.builtin.command:
            cmd: goss --gossfile - validate
            stdin: "{{ lookup('template', 'goss/users.yml.j2') }}"
