---

- name: haproxy reload
  ansible.builtin.service:
    name: "{{ item }}"
    state: reloaded
  loop:
    - haproxy

- name: haproxy restart
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - haproxy
