---

- name: Tasks / Command
  tags:
    - manala_deploy
  block:

    - name: Tasks / Command > "{{ item.options }}" in "{{ item.dir }}"
      ansible.builtin.command: "{{ item.options }}"
      args:
        chdir: "{{ item.dir }}"
      changed_when: true
