---

- name: Tasks / Make
  tags:
    - manala_deploy
  block:

    - name: Tasks / Make > "{{ item.options }}" in "{{ item.dir }}"
      ansible.builtin.command: "make {{ item.options }}"
      args:
        chdir: "{{ item.dir }}"
      changed_when: true
