---

- name: tasks/service_restart
  tags:
    - manala_deploy
  block:

    - name: tasks/service_restart > "{{ item.options }}"
      ansible.builtin.service:
        name: "{{ item.options }}"
        state: restarted
