---

- name: tasks/service_reload
  tags:
    - manala_deploy
  block:

    - name: tasks/service_reload > "{{ item.options }}"
      ansible.builtin.service:
        name: "{{ item.options }}"
        state: reloaded
