---

###########
# Default #
###########

- name: Default
  tags: [default]
  hosts:
    - debian.stretch
  tasks:
    - block:  # noqa unnamed-task
        - name: Role
          ansible.builtin.import_role:
            name: manala.roles.elasticsearch
          vars:
            manala_elasticsearch_plugins:
              - mobz/elasticsearch-head
      always:
        - name: Wait for pretty response
          ansible.builtin.uri:
            url: http://localhost:9200/?pretty
          register: result
          until: result.status == 200
          retries: 60
          delay: 1
        - name: Goss
          ansible.builtin.command:
            cmd: goss --gossfile - validate
            stdin: "{{ lookup('template', 'goss/default.yml.j2') }}"
          changed_when: false
