---

- name: update > Pull
  ansible.builtin.shell: |
    docker images \
      | awk '/^REPOSITORY|\<none\>/ {next} {print $1":"$2}' \
      | xargs --max-args=1 --max-lines=1 --no-run-if-empty docker pull
  tags:
    - skip_ansible_lint
