---

##############
# Selections #
##############

- name: Selections
  tags: [selections]
  hosts: debian
  tasks:
    - name: Packages
      ansible.builtin.apt:
        name: [nano, ed, less]
        install_recommends: false
        update_cache: true
        cache_valid_time: 3600
    - name: Alternatives
      alternatives:
        name: "{{ item[0] }}"
        path: "{{ item[1] }}"
      loop: [[editor, /bin/nano], [pico, /bin/nano], [pager, /bin/more]]
    - block:
        - name: Role
          ansible.builtin.import_role:
            name: manala.roles.alternatives
          vars:
            manala_alternatives_selections:
              - selection: editor
                path: /bin/ed
              # Flatten
              -
                - selection: pico
                  path: /bin/ed
              # State
              - selection: pager
                path: /bin/less
                state: ignore
      always:
        - name: Goss
          ansible.builtin.command:
            cmd: goss --gossfile - validate
            stdin: "{{ lookup('template', 'goss/selections.yml.j2') }}"
