---

###########
# Default #
###########

- name: Default
  tags: [default]
  hosts: debian
  tasks:
    - block:
        - name: Role
          ansible.builtin.import_role:
            name: manala.roles.fail2ban
          vars:
            manala_fail2ban_config: |
              [ssh]
              enabled = false
              [sshd]
              enabled = false
      always:
        - name: Goss
          ansible.builtin.command:
            cmd: goss --gossfile - validate
            stdin: "{{ lookup('template', 'goss/default.yml.j2') }}"

##########
# Config #
##########

- name: Config
  tags: [config]
  hosts: debian
  vars:
    tests_dir: /molecule/fail2ban/config
  tasks:
    - name: Clean tests dir  # noqa risky-file-permissions
      ansible.builtin.file:
        path: "{{ tests_dir }}"
        state: "{{ item }}"
      loop: [absent, directory]
    - block:
        - name: Role - Content
          ansible.builtin.import_role:
            # Play role fully on first run, so that handlers don't breaks
            name: manala.roles.fail2ban
          vars:
            manala_fail2ban_config_file: "{{ tests_dir }}/content"
            manala_fail2ban_config_template: ~
            manala_fail2ban_config: |
              Content
        - name: Role - Template
          ansible.builtin.import_role:
            name: manala.roles.fail2ban
            tasks_from: config
          vars:
            manala_fail2ban_config_file: "{{ tests_dir }}/template"
            manala_fail2ban_config_template: fixtures/template.j2
            manala_fail2ban_config: ~
      always:
        - name: Goss
          ansible.builtin.command:
            cmd: goss --gossfile - validate
            stdin: "{{ lookup('template', 'goss/config.yml.j2') }}"
