---

###########
# Default #
###########

- name: Default
  tags: [default]
  hosts: debian
  tasks:
    - block:
        - name: Role
          import_role:
            name: manala.roles.mysql
          vars:
            manala_mysql_install_packages:
              - mariadb-server
              - mariadb-client
            manala_mysql_users:
              - name: foo
                password: foo
                login_unix_socket: /var/run/mysqld/mysqld.sock
                priv: "*.*:ALL,GRANT"
              - name: bar
                state: ignore
              # Flatten
              -
                - name: baz
                  password: baz
                  login_unix_socket: /var/run/mysqld/mysqld.sock
                  priv: "*.*:ALL,GRANT"
            manala_mysql_databases:
              - name: foo
                login_unix_socket: /var/run/mysqld/mysqld.sock
              - name: bar
                login_unix_socket: /var/run/mysqld/mysqld.sock
                state: ignore
              # Flatten
              -
                - name: baz
                  login_unix_socket: /var/run/mysqld/mysqld.sock
      always:
        - name: Goss
          command:
            cmd: goss --gossfile - validate
            stdin: "{{ lookup('template', 'goss/default.yml.j2') }}"
