name: Molecule - MySQL

on:
  workflow_dispatch:
    inputs:
      debug:
        description: Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)
        required: false
        default: false
