name: Molecule - NodeJS

on:
  pull_request:
    paths:
      - .manala.yaml
      - .github/workflows/molecule.nodejs.yml
      - .config/molecule/config.yml
      - molecule/Dockerfile.*
      - molecule/nodejs.*/**
      - roles/nodejs/**
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Run with tmate debugging
        required: false
        default: false

jobs:
  nodejs:
    uses: ./.github/workflows/molecule.yaml
    with:
      debug: ${{ inputs.debug == true }}
      scenario: nodejs
      versions: '[14, 16]'
