name: Molecule - MongoDB

on:
  pull_request:
    paths:
      - .github/workflows/molecule.mongodb.yml
      - .config/molecule/config.yml
      - molecule/Dockerfile.*
      - molecule/mongodb.*/**
      - roles/mongodb/**
      # Plugins
      - plugins/filter/staten.py
      - plugins/filter/yaml.py
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Run with tmate debugging
        required: false
        default: false

jobs:
  mongodb:
    uses: ./.github/workflows/molecule.yaml
    with:
      debug: ${{ inputs.debug == true }}
      scenario: mongodb
      versions: '[3.6]'
