---

- hosts:
    - debian.buster
    - debian.bullseye
  tags: [always]
  tasks:
    - name: Apt
      ansible.builtin.import_role:
        name: manala.roles.apt
      vars:
        manala_apt_preferences:
          - redis@backports
      when: ansible_distribution_release in ['buster']
