---

- name: php fpm restart
  ansible.builtin.command: >
    /usr/sbin/php-fpm{{ manala_php_version|string }} -t
  when: |
    'fpm' in query(
      'manala.roles.php_sapis',
      manala_php_sapis|default(manala_php_sapis_default, True),
      manala_php_sapis_available,
      wantstate='present',
      wantmap=true
    )
  changed_when: true
  listen: php restart
  notify:
    - do php fpm restart

- name: do php fpm restart
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - php{{ manala_php_version|string }}-fpm
  when: |
    'fpm' in query(
      'manala.roles.php_sapis',
      manala_php_sapis|default(manala_php_sapis_default, True),
      manala_php_sapis_available,
      wantstate='present',
      wantmap=true
    )

- name: php blackfire agent restart
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - blackfire-agent
